#+OPTIONS: num:nil toc:nil ^:nil
#+TITLE: Shells, Terminals and the future that never was
#+AUTHOR: Bence Fabián <bence.fabian@codecool.com>

* Punched Cards
  Punched cards were first used for looms.

  Used in early computers to enter text.
* Punched Cards
  That was one line:

  - Every column a character
  - Every row a bit

  And this is why still to this day lines are 80 columns long.
* Teletypes
  Machines using paper feed.

  Editing was line by line.

  The origin of the name =/dev/tty=.
* Teletypes
  Let's see how editing looked like back then.
* Teletypes
  Oldschool ed only wrote a question mark in this case...

  Let's enter append mode.
* Teletypes
  Now we can enter our program
* Teletypes
  Let's exit append mode.

  With a single dot.

  (good luck if you want to *insert* a single dot on a line)
* Teletypes
  Say we want to refactor =i= into something more meaningful.
* Teletypes
  And now print it.
* Teletypes
  Oh /noooooo/!

  We messed up.

  Let's undo and retry with a better matcher.
* Teletypes
  So easy...

  Let's save and never come back.

  _NOTE_: ed was *much* better than its contemporaries and still has
  some uses today.  For example in shell scripts because it consumes
  commands as a text stream.
